[project]
name = "hoverpower"
version = "1.6.1"
description = ""
requires-python = ">=3.12"
authors = [
    { name = "Helmut Konrad Schewe", email = "helmutus@outlook.com" },
]
dependencies = [
    "resinf>=1.0.4,<2.0.0",
    "jamer>=1.0.2,<2.0.0",
    "utilo>=2.109.0,<3.0.0",
    "cryptography>=38.0.0,<49.0.0",
]
keywords = []
classifiers = [
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
license = "MIT"
license-files = [
    "LICENSE",
]

[project.readme]
file = "README"
content-type = "text/markdown"

[project.optional-dependencies]
dev = [
    "utilotest>=1.0.4,<2.0.0",
    "pdflog==1.0.2",
]

[project.urls]
Homepage = "https://github.com/anaticulae/hoverpower"
Repository = "https://github.com/anaticulae/hoverpower"

[project.scripts]
give = "hoverpower.cli.give:main"
power = "hoverpower.cli:main"
powercompress = "hoverpower.cli.compress:main"
powerdecrypt = "hoverpower.cli.decrypt:main"
powerdownload = "hoverpower.path:download_packages"
powerencrypt = "hoverpower.secret:make_private"
powersecret = "hoverpower.secret:create_secret"

[build-system]
requires = [
    "setuptools>=82.0.1",
    "wheel>=0.46.3",
]
build-backend = "setuptools.build_meta"

[tool.semantic_release]
version_toml = [
    "pyproject.toml:project.version",
]

[tool.semantic_release.changelog]
mode = "init"
output_format = "md"

[tool.semantic_release.changelog.default_templates]
changelog_file = "CHANGELOG"

[tool.semantic_release.commit_parser_options]
patch_tags = [
    "build",
    "chore",
    "ci",
    "deps",
    "docs",
    "fix",
    "perf",
    "refactor",
    "style",
    "test",
]
minor_tags = [
    "feat",
]

[tool.setuptools.packages.find]
where = [
    ".",
]
include = [
    "hoverpower",
    "hoverpower.cli",
    "hoverpower.repo",
]
exclude = [
    "tests/*",
]
